### ISSUE TITLE
 Power Plant Enhancer

### ISSUE THREAD

**Issue by Dr-Harbinger** [Phobos-developers/Phobos#134] opened 2021-04-04 11:52 UTC
_Introduce Power Plant Enhancer to Phobos_
Power plant enhancer is some sort of structure or a plug-in. When it exists, it can increase the power amount generated by the plants. When buffer structures are sold or destroyed, the power amount returns to normal. This buff can overlay  as the number of enhancers grows.

`[BuildingType]> CanChangeBuildingPower=(boolean); Whether this structure can change the power of other structures.
[BuildingType]> ChangePower.Buildings=(list of BuildingTypes);  List of structures which can change the power.
[BuildingType]> ChangePower.PowerSet= (integer - percent); Changed power amount which can be plus or minus.`

**Comment by Metadorius** [comment] 2021-04-04 11:54
Duplicate of #131.

**Closed by Metadorius** 2021-04-04 11:54 UTC
Labels: Dupe
