### ISSUE TITLE
DIY Unit Trailer Animation Location & Multiple Trailer Settings

### ISSUE THREAD

**Issue by Dr-Harbinger** [Phobos-developers/Phobos#146] opened 2021-04-07 02:18 UTC
_Introduce DIY Unit Trailer Animation Location and Multiple Trailer Settings to Phobos_
This allows users to customize the location of trailer animation and to add multiple trailers to a unit.
```ini
[VehicleArt]> Trailerlocation=F,L,H  ; (integer) 

                          Traile2=      
			  Trailer2Seperation= 
			  Trailer2location=

			  ......
```

**Comment by ayylmaoRotE** [comment] 2021-04-07 02:26
Issue https://github.com/Phobos-developers/Phobos/issues/9

**Comment by Thrifinesma** [comment] 2021-04-07 08:14
Duplicate of #9

**Closed** 2021-04-07 08:14 UTC
Labels: Dupe
