### ISSUE TITLE
FixTransparencyBlitters cause flickering in the last few frames of long translucent animations

### ISSUE THREAD

**Issue by Duck-Wang** [Phobos-developers/Phobos#730] opened 2022-08-21 14:53 UTC
### First check

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

### Description

After using FixTransparencyBlitters=yes on build 29 of Phobos, the last few frames of a translucent animation with many frames will have a transparency bug causing flickering. (The number of animation frames in the gif is 105.)
![2](https://user-images.githubusercontent.com/81621599/185796528-0a4caad6-86a0-4488-8e32-4f00cbd3b6c2.gif)

### Phobos Version

https://github.com/Phobos-developers/Phobos/releases/tag/build-29

### INI code

```ini
In art:
[SMOKE01]
Image=SMOKE01
Rate=450
LoopCount=1
Translucent=yes
Shadow=no
```

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

disappear normally
![1](https://user-images.githubusercontent.com/81621599/185796729-629ff9b5-3baa-4300-b97c-dd5eea188bd4.gif)

### Actual behaviour

as described above

**Comment by Starkku** [comment] 2022-08-21 16:26
I suspect this is related to a specific caveat of the `FixTransparencyBlitters`, which is not explained in a particularly large amount of detail in the documentation (but is still mentioned). Specifically it will only apply to SHPs using RLE compression. It is possible for individual frames of SHP to be saved using different compression settings, which could explain what is happening here as it alternates between the fixed and original transparency algorithm creating a blinking effect

Resave the SHP so that RLE compression is applied (in SHP Builder the appropriate setting would be `Force Compression 3`) and confirm if it is fixed or alternatively provide the SHP file used so someone else can confirm this on your behalf.

**Comment by Duck-Wang** [comment] 2022-08-21 22:58
Yes, you are right. It worked fine after saving with RLE compression.

**Comment by Starkku** [comment] 2022-08-22 10:59
Alright, closing this as it is not a bug. Might adjust documentation to be more clear on this though.

**Closed by Starkku** 2022-08-22 10:59 UTC
Labels: Phobos bug
