### ISSUE TITLE
[New Feature] Referenceable sections 

### ISSUE THREAD

**Issue by Talafhah1** [Phobos-developers/Phobos#481] opened 2021-12-23 17:11 UTC
Allows sections to be reference in other sections similarly to Ares' `[#include]`.  This allows for less copy/pasting for similar sections that share most of their code but only has a few things changed.  It also makes balancing and changing values less tedious if many variants of the same thing exist and reduces the chances of stat-related bugs/oversights.
Values after the reference will override the reference, and values before will be overridden.

```ini
[M60]
Damage=15
ROF=20
Range=4
Projectile=InvisibleLow
Speed=100
Warhead=SA
Report=GIAttack
Anim=MGUN-N,MGUN-NE,MGUN-E,MGUN-SE,MGUN-S,MGUN-SW,MGUN-W,MGUN-NW
OccupantAnim=UCFLASH

[M60E]
#M60
Damage=25
```

**Comment by Thrifinesma** [comment] 2021-12-24 03:16
Currently, we have Ares' `[A]:[B]` in this usage

**Comment by SethGekco** [comment] 2021-12-24 04:36
Doesn't that have bugs thus the desire to not use them? Anyway to make it so they require prerequisites as well in order to allow modders to expand upon Industrial Plants like structures (like say if users want to reduce vehicle initial health?)?

**Comment by Metadorius** [comment] 2022-01-11 12:46
Duplicate of #288

**Closed by Metadorius** 2022-01-11 12:46 UTC
Labels: Feature / Enhancement
