### ISSUE TITLE
`IronCurtain effects on organics' feature not working in v0.3.0.1

### ISSUE THREAD

**Issue by kotoricon** [Phobos-developers/Phobos#1127] opened 2023-08-12 11:38 UTC
### Description

Only test build 36 work, v0.3.0.1 will instant kill every infantry with IronCurtain effects.
Last time I've tested this in 0.3.0.0 also have the same bug. only work in other test build like build 33/34/35 etc.

### Phobos Version

0.3.0.1

### Steps to reproduce

Like the discord channel said.

### Expected behaviour

Like the discord channel said.

### Actual behaviour

Like the discord channel said.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Fryone** [comment] 2023-08-12 15:38
It it not a bug, it's a test feature for debug builds, and will be in post 0.3 versions. 0.3.0.1 has only 0.3 features.

**Comment by Metadorius** [comment] 2023-08-12 15:44
Wait, it was merged past 0.3? I thought the opposite and instructed to make this issue. Apologies then, closing.

**Closed by Metadorius** 2023-08-12 15:44 UTC
Labels: Phobos bug
