### ISSUE TITLE
[Phobos Bug] PassengerDeletion.Rate does not work properly

### ISSUE THREAD

**Issue by Cpj636** [Phobos-developers/Phobos#474] opened 2021-12-16 11:13 UTC
### Description:
It seems that this tag will not be read. No matter what kind of integer assigned, the passenger will be directly deleted.

### Expected Behaviour:
The passenger should be deleted after the frame assigned.

**Comment by FS-21** [comment] 2022-01-11 18:27
Can you try this build?
https://nightly.link/Phobos-developers/Phobos/actions/artifacts/140807647.zip

Comes from:
https://github.com/Phobos-developers/Phobos/pull/498

**Comment by Cpj636** [comment] 2022-01-12 12:15
Sure, it works as expected. Wish it's possible to add another tag like "PassengerDeletion.AffectsHouse" so that we can restrict the deletion of enemies only, by which way the MindControl problem for opentopped units can also be partially solved.

**Comment by Metadorius** [comment] 2022-01-12 12:20
Closing as the issue is resolved.

**Closed by Metadorius** 2022-01-12 12:20 UTC
Labels: Phobos bug
